version: '3'

services:
  palmon_front:
    build:
      context: front
    container_name: palmon_web
    restart: always
    volumes:
      - ./front/src/:/usr/local/apache2/htdocs
    ports:
      - ${WEB_PORT}:80
    networks:
      - palmon-network

  palmon_backend:
    image: fastapi
    build:
      context: back
    env_file:
      - .env
    container_name: palmon_backend
    restart: always
    ports:
      - ${BACK_PORT}:80
    networks:
      - palmon-network

  palmon_service_eggs:
    build:
      context: services/eggs
    env_file:
      - .env
    container_name: palmon_service_eggs
    restart: always
    ports:
      - ${EGGS_SERVICE_PORT}:80
    networks:
      - palmon-network
    hostname: palmon_service_eggs

  palmon_database_eggs:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: palmon_database_eggs
    restart: always
    environment:
      - MYSQL_USER=${SERV_EGGS_SQL_USER}
      - MYSQL_PASSWORD=${SERV_EGGS_SQL_PASSWORD}
      - MYSQL_DATABASE=${SERV_EGGS_SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SERV_EGGS_SQL_ROOTPASSWORD}
    volumes:
      - ${SERV_EGGS_SQL_DATA_PATH}:/var/lib/mysql/
    networks:
      - palmon-network
    hostname: palmon_database_eggs

  palmon_service_fights:
    build:
      context: services/fights
    env_file:
      - .env
    container_name: palmon_service_fights
    restart: always
    ports:
      - ${FIGHTS_SERVICE_PORT}:80
    networks:
      - palmon-network
    hostname: palmon_service_fights

  palmon_service_palmons:
    build:
      context: services/palmons
    env_file:
      - .env
    container_name: palmon_service_palmons
    restart: always
    links:
      - palmon_database_palmons
    depends_on:
      - palmon_database_palmons
    volumes:
      - ./.env:/.env
    ports:
      - ${PALMONS_SERVICE_PORT}:80
    networks:
      - palmon-network
    hostname: palmon_service_palmons

  palmon_database_palmons:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: palmon_database_palmons
    restart: always
    environment:
      - MYSQL_USER=${SERV_PALMON_SQL_USER}
      - MYSQL_PASSWORD=${SERV_PALMON_SQL_PASSWORD}
      - MYSQL_DATABASE=${SERV_PALMON_SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SERV_PALMON_SQL_ROOTPASSWORD}
    volumes:
      - ${SERV_PALMON_SQL_DATA_PATH}:/var/lib/mysql/
    networks:
      - palmon-network
    hostname: palmon_database_palmons

  palmon_service_shop:
    build:
      context: services/shop
    env_file:
      - .env
    container_name: palmon_service_shop
    restart: always
    ports:
      - ${SHOP_SERVICE_PORT}:80
    networks:
      - palmon-network
    hostname: palmon_service_shop

  palmon_database_shop:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: palmon_database_shop
    restart: always
    environment:
      - MYSQL_USER=${SERV_SHOP_SQL_USER}
      - MYSQL_PASSWORD=${SERV_SHOP_SQL_PASSWORD}
      - MYSQL_DATABASE=${SERV_SHOP_SQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SERV_SHOP_SQL_ROOTPASSWORD}
    volumes:
      - ${SERV_SHOP_SQL_DATA_PATH}:/var/lib/mysql/
    networks:
      - palmon-network
    hostname: palmon_database_shop

  # palmon_phpmyadmin:
  #   env_file:
  #     - .env
  #   image: phpmyadmin/phpmyadmin
  #   container_name: palmon_phpmyadmin
  #   restart: always
  #   depends_on:
  #     - palmon_database
  #   links:
  #     - palmon_database
  #   environment:
  #     PMA_HOST: palmon_database
  #     PMA_USER: root
  #     PMA_PASSWORD: ${SQL_ROOTPASSWORD}
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   networks:
  #     - palmon-network
  #   ports:
  #     - ${PMA_PORT}:80

  
networks:
  palmon-network:
    name: palmon-network
    driver: bridge